### ISSUE TITLE
Hard negative mining

### ISSUE THREAD

**Issue by ruanchaves** [izuna385/Dual-encoder-Entity-Retrieval-with-BERT#2]
It seems to me that hard negative mining is not implemented on this repository, although it is implemented on [izuna385/Zero-Shot-Entity-Linking](https://github.com/izuna385/Zero-Shot-Entity-Linking) . Am I right?

**Comment by izuna385** [comment]
You're right. That was implemented [here](https://github.com/izuna385/Zero-Shot-Entity-Linking/blob/master/src/hardnegative_searcher.py#L56).
Thanks.
